trigger:
- main

pool:
   vmImage: 'ubuntu-latest'

variables:
- group: SECRETS

stages:
- stage: Build
  displayName: 'Stage 1 - Build'
  jobs:
  - job: BuildJob
    displayName: 'Build and Test'
    steps:

    - script: |
        java -version
        mvn -version
      displayName: 'Check Java and Maven Installation'

    - task: Maven@3
      displayName: 'Maven Build (Clean Package)'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    # Publish artifact only if build succeeds
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Build Artifact'
      condition: succeeded()
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/target'
        artifact: 'student-app-jar'


- stage: Release
  displayName: 'Stage 2 - Release'
  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: ReleaseJob
    displayName: 'Download and Deploy'
    steps:


    - task: DownloadPipelineArtifact@2
      displayName: 'Download Artifact'
      inputs:
        artifactName: 'student-app-jar'
        targetPath: '$(Pipeline.Workspace)/student-app-jar'


    - script: |
        echo =======================
        echo KSIT DevOps Lab - Release
        echo =======================

        echo App Version : $(appVersion)
        echo Deploy Key  : $(deployKey)

        echo Listing files:
        ls -R $(Pipeline.Workspace)/student-app-jar

        echo Deployment Completed Successfully
      displayName: 'Simulate Deployment'